---
title: (working title) Control mechanisms for working with consultants
biblio-style: unsrt
csl: apa.csl
blinded: 0
link-citations: yes
linkcolor: blue
authors: 
- name: Roel Peters
  affiliation: Antwerp Management School
bibliography: references.bib
output: rticles::asa_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

# Relevancy

1.  Trend: external \> internal
2.  Price of consultants
3.  Hot topic: *when* to rely on consultants?
4.  Productivity: is it worth it? If so, under what circumstances?
5.  Job market & macro-economic aspects
6.  Recent news in BE/NL

# Defining "Digital Consultancy"

"Digital consultancy" is defined as consultancy in (either or both) technological and organizational aspects of digital transformation. The following two sections substantiate this definition by elaborating on the two concepts that comprise this definition. First, six properties that define "consultancy" are discussed, followed by an elaboration on "digital transformation."

## Consultancy

Consultants, or management consultants, have been described through a multitude of metaphors and nicknames: "capitalism's commissars" [@thrift2005 93], "shadowy figures operating in the background but exercising considerable influence" [@kipping2012 31], "agents of a modern rationalistic and universalistic culture" [@kipping2012 190], "institutionally approved agents" [@kipping2012 193], "marketized experts" [@furusten2012 265], "magical figures, shamans or witch doctors" [@fincham2002 68], "puppet masters" [@fincham2002 69], "knowledge entrepreneurs that promote emotionally charged, enthusiastic, and unreasoned discourse" [@leicht2006 37], "supra-experts" [@kieser2006 94], "improvising experts" [@furusten2009 272] and simply "The Big Con" [@mazzucato2023].

Their work makes use of a vague body of knowledge described as "elusive", "fuzzy", "perishable", "indeterminate", "esoteric", "fluid" and "changeable" [@muzio2011]. Consequently, for buyers it is hard to know what they need and what they get, and for sellers of consultancy it is hard to know what to offer [@furusten2012 266]. Furthermore, consultancy is marked by very low professionalization since occupational entry is unprotected, the supply of labor is unregulated and there is no formal accreditation. [@fincham2006 20] Practicing "consultancy" is the main criterion of membership with competences and "time spent in the industry" as the main differentiators.

These remarks are prima facie evidence that no consensus around the definition exists, and what they do is extremely hard to describe. @kipping2012 [24] states that "definitions of management consultancy are problematic because the permeable boundaries of the industry have resulted in significant shifts over time in the composition of the industry. This means that what comprises consulting work is dynamic, ever shifting, and contested as new firms enter the industry and techniques deemed formerly appropriate, change. Although the industry is characterized by periodic structural shifts, at its heart it is an advisory activity built on the client--consultant relationship. [...] it is perhaps this chimeral ability to avoid precise definition and to be able to constantly reinvent its core services to meet ever changing understandings of the problems that beset contemporary organizations, which partly underpins its growing economic importance."

The following definition of "consultancy" is used throughout this paper.

> *Consultancy is a service offered by an external service provider. Although the responsibilities of a consultant are highly contingent on the client organization and consultancy can take many forms and require a variety of expertise, its goals is to establish change in the procedures, organizational structure or tools of a client organization. Finally, the success of a consultancy engagement is often determined by the interactivity between a consultancy firm and the client organization.*

The sections below unpack this definition and elaborate on the six properties that it comprises.

### External

@chowdhury2021 [138] describes consultants as "external advisors to corporations, nonprofits, governments, and any other forms of organizations."

### Change

Clearly, the construct of a "consultant" cannot be described by the topic that they work on, nor their academic and professional background, accreditation or membership. Instead, we should look at their goal(s): @werr1986 [1] implies that there is always a change process between clients and consultants. This is confirmed by @kipping2000 [12] who states that "management consultancies earn money through changing current procedures in client organizations." Although this change is often described by consultants as a 'tailored solution', consultants provide a service, which is inherently intangible (compared to the 'solid' nature of products) and hard to evaluate [@fincham1999 348], especially because an evaluation should not only account for the content of the changes, but also in terms of the competence development of the client, as a result of the change process [@werr1986 17].

Although consultants' goal is to establish change in an organization, their role is often symbolic. As external consultants, associated with their "quest for knowledge" and their "quest for excellence", they are [@pellegrin2006 9-13] well-equipped for legitimizing hard decisions, signaling importance and providing meaning.

Establishing change is what sets consultancy apart from temporary staffing. "A temp is generally not supposed to change the work practices at the client organization. A consultant is often expected to do just that, or at least to provide an alternative point of view." [@furusten2000 5]

The aspect of change is also important for drawing boundaries between consultancy and outsourcing. Consultants are often hired for defining a problem and presenting a solution at the same time [@furusten2009 272], while outsourcing simply delivers the solution. In that sense, outsourcing is the practice of obtaining goods or services from an external provider, as a substitute for sourcing it internally [@lacity2012 2], for a contractually agreed monetary fee and period of time [@leimeister2010 20-21]. Or in the words of @zhu2001 [374]: "the process of transferring the responsibility for a specific business function from an employee group to a non-employee group." While early IT outsourcing initiatives were rather "total" @willcocks1995 in nature, outsourcing individual business functions is now a more common activity [@zhu2001 377], and focus has shifted from cost saving to quality, productivity, flexibility and technological diversity [@kirilov2012 185]. This implies that outsourcing, unlike consultancy, is not about changing a procedure or service, but rather ensuring continuation, or implementation, by a third-party provider[^1].

[^1]: *Prima facie*, this could be interpreted as a departure from the work by @loh1992 and @venkatraman1994, who claim that IT outsourcing is an "administrative innovation, [...] involving significant changes in the routines used by the organization to deal with its tasks of internal arrangements and external alignments." However, while there is indeed a firm-level change [@nelson1985 14], in the sense of who is responsible for a specific (part of a) procedure, the procedure or service involved does not change *an sich.*

Finally, @furusten2009 [272-273] argues that consultants not only act as agents of change, but often as agents of stability. Consultants are often perceived as "relatively stable by [...] employees, stakeholders and other external counterparts", this "builds confidence for the organization. The more stable an organization is experienced as being, the greater its ability to concentrate on its core activities."

### Contingent

Being a consultant implies taking on a variety of responsibilities throughout a certain time span. Although many consultants have structured methodologies, which are converging across the industry [@werr1986 17], "[c]onsultants operate in an intense environment that regularly entails new challenges." [@chowdhury2021 138] What entails consultancy work is dynamic, ever shifting and contested with every new firm entering the industry and new methodologies claiming the spotlight [@kipping2012 24].

This is what sets external consultancy apart from internal consultancy.

### Relational

The nature of consultancy is often relational. First of all, a consultant's work is embedded in an organization's web of interpersonal relations. "[T]he context, terms of reference, and ensueing recommendations pertaining to a consultancy engagement may represent a continuation, by other means, of ongoing processes of co-operation, struggle and conflict between organizational groups." [@bloomfield1995]

Furthermore, a consultant's deliverable is often co-created with the client. @nikolova2009 [290-297] describes the client-consultant relationship within a 'social learning model'. It starts from the belief that there is no "knowledge out there", and client and consultant need to work closely together to develop problem solutions. The role of the consultant is that of a "facilitator of diagnosis and problem-solving" and coach, while the client is the actual problem solver. @clark1998 [22] even goes so far as to claim that "Like a bottle of wine, a restaurant meal, or a book, the quality of a management consultancy service is determined during enactment/consumption. This indicates that the outcome of a consultancy service is highly dependent upon the quality of the interaction between the client and the consultant."

A consultant needs to develop skills in order to fit in and adapt their skill set to the needs of a client. When a relationship does not succeed, no authority is placed on the skills of the service provider [@furusten2000 10] and the assignment might turnout to be unsuccessful. In other words, a consultant is good at improvising: "when they do not really know what problem the client has or how to solve it, to improvise and act in a manner they believe the other party expects of them in a particular situation is a convenient way for both parties to muddle through." [@furusten2009 270]

The importance of the relational aspect again sets consultancy apart from outsourcing [@kipping2012 171-173]. The outcome of a consultancy assignment often depends heavily on the interaction between the client and the service provider. On the other hand, outsourcing focuses more on technical capabilities and implies an integral handover of a (set of) service(s) to an external provider that becomes the sole responsible for delivering them. Nevertheless, one could argue that the implementation phase of a consultancy engagement offers the same benefits as outsourcing certain IT functions. For this reason, where appropriate, this study also uses insights from literature that focuses on IT outsourcing.

Finally, the relational aspects also sets consultancy apart from auditing, for which "[i]ndependence is necessary to prevent auditors from biasing their opinions in favor of their clients." [@bazerman2011 310] In other words, to prevent client pressure leading to client pleasing by the auditor [@koch2017], audit engagements shouldn't be relational, on the contrary.

### Two-sided

Besides their tasks at the client, consultants also face internal pressures from their employers in terms of optimized resource utilization (billabillity), using proprietary knowledge and "proximity that they can develop with the client." @chowdhury2021 [138] In other words, a consultant serves two masters: the client organization, and the organization that pays their wage. While the former expects an adequate service, the latter has a commercial motive. [@furusten2012 270]

Two-sidedness is what sets external consultants apart from internal consultants, but also from temporary staff. If a worker or contractor is under the direct supervision of the organization it is working for, it is seen as temporary staffing or "staff augmentation." [@hodosi2019 1]

### Diverse

Within this group, however, we can identify consultancy types: strategy consulting, tax consulting, HR consulting, risk & regulatory consulting, etc. However, @armbruster2006 [71-72] argues that the boundaries between consultancy service types are blurred. A single project often requires multiple types of services, but the distinction is often artificial. Especially the boundary between strategy and IT consultancy is opaque due to the fact that the big accounting & strategy firms entered the IT consultancy market to conduct all-encompassing projects where strategy and IT meet.

## Digital Transformation

@bloomfield1995 [28] describes IT consultants as intermediaries: "they interpose themselves between IT and clients, or between IT suppliers and clients, in effect seeking to speak for technology. Put another way, they seek to portray them selves as obligatory passage points. [...] the problem of choosing a particular functional system is translated into a problem of choosing the best expert advice."

However, the offering by many different types of organizations of some kind of IT consultancy for selecting, implementing, configuring and preaching IT solutions has led to a blurring of consultancy work [@bloomfield1995 31; @kipping2012 162]. While consultants working for hardware and software vendors are claimed to be motivated by the sale of their own products, consultancy firms aim to equal themselves as suppliers of objective business advice.

These blurring lines are the result of the fact that there is more than a technical dimension to IT solutions. Consequently, consultants frame IT solutions not just from their technical dimension, but from their organizational dimension, as well [@bloomfield1995 24-25]. Like strategy, technology, often depicted as neutral and separate from social or political matters, can be wielded for political purposes. However, the boundary between the merely technological and political is flexible: a social or political problem can be translated as a technical one.

In accordance with this interpretation, the services of multinational consultancy firms are defined or classified as consultancy in digital operations (PwC); digital commerce & engineering (Accenture); digital transformation (EY, Bain, Deloitte, Tata); digital (McKinsey, KPMG); digital, technology & data (BCG); digitalization (Capgemini), digital solutions (BoozAllenHamilton) and digital experience (Cognizant). Ergo, it is remarkable that many research describes this group of consultants as "IT consultants" [@nevo2007; @loh1992; @fincham2006; @armbruster2006; @bloomfield1995; @schwarz2005], while none of the big consultancy firms offer "IT consultancy". @czerniawska1999 [96] abandons the term and trades it in for "IT-related consultancy".

Mindful of these findings, this paper trades in the concept of "IT consultancy" for "digital consultancy", and defines it as follows.

> *Digital consultancy is consultancy in (either or both) technological and organizational aspects of digital transformation*.

In this definition "digital transformation" refers to the expectation that the use of digital technology will lead to favorable business outcomes [@wessel2020 104-118], by redefining or supporting the value proposition of an organization and imposing changes on the work practices of its organizational members. Proceeding forward, this interpretation rolls up the dichotomy between the concepts of "digital transformation" and "IT-enabled organizational transformation" into a single term.

# Emergence of Digital Consultancy

## The Pioneers of Consultancy

## The Ascent of Consultancy

### The Macro-economic Context: Supply-Side Economics

The post-bureaucratic organization "invites market dynamics into what used to be intra-organizational matters and seeks to rid the organization of activities that are not directly linked to its focal service or product." [@furusten2000 3]

Specifically for public sector use of consultants, @ylonen2019 [242] use the term 'consultocracy'; the "phenomenon in which often short-term, outsourced expert knowledge production is increasingly replacing the long-term work of civil servants and even politicians. This results in an increased power of consultants over politics, public governance, and public sector practices."

@ylonen2019 [250] argues that the increasing reliance on consultants results in the loss of tacit knowledge in the public sector: "The old bureaucratic virtues erode as informal trust and information lose their organizational structures and channels." The culprit is usually found in cost-cutting programs that generate pressure to eliminate permanent work hours. However, it "can also be advanced as a hidden or explicit political agenda. [...] major organizational overhauls were often motivated by the desire to destruct existing organizational structures. Constant change was desirable precisely because it helped to shatter old ways of working."

Finally @ylonen2019 [252] describes how the increasing use of consultancy weakens accountability of civil servants as responsibilities are transferred to consultancy firms. Furthermore, in many countries, contracts between the government and consultants are negotiated under private law, putting severe limits on the public availability of relevant documents.

### The Micro-economic Context: Radical Reflexivity

"Intrinsic to radical reflexivity is an 'unsettling,' i.e., an insecurity regarding the basic assumptions, discourse and practices used in describing reality." [@pollner1991 370]

A factor contributing to the emergence of "professional service firms" is the "downsized, outsourced, subcontracted and global environment for business services overall." [@leicht2006 17]

"Markets may represent a new organizational logic, but markets do not speak very clearly nor do they provide elite managers with clear guidance regarding the directions markets are heading in specific contexts. [...] The institutional context is ripe for the rise of management consulting as the profession that 'interprets markets for you.' The irony of this is that markets were supposed to obviate the need for professional expertise. But what the recent changes in institutional, societal logic have done is replace one set of ideologies (professional institutions and practices as protectors of the public good) with another one (markets as protectors of the public good). The ability to institutionalize this professional role will depend on the willingness of top corporate managers to pay for these types of services and the ability of management consultants to prove that they can deliver measurable results (higher profits; avoidance of legal and reputational trouble, etc.)." [@leicht2006 37]

Some papers to explore:

-   [@armbruster2006 120-130].
-   [@kipping2003]
-   [@kipping2012]
-   [@fincham1999 336]
-   [@mckenna2006]

"Companies with effective in-house management or which operate in areas of relative commercial stability may not need to employ consultancies. Nevertheless, positive attitudes to consultancies and good practice in their use appear particularly to be associated with rapidly changing corporations. It appears that, within the context of growing competition, the use of consultancies is a symptom of a much broader sea-change in modern management approaches which underlies growing instability in regional and local economies." [@wood1996 662]

### Digital Consultancy: A Logical Progression

Three phases can be identified.

In the first phase, consultants were working with the first commercially usable computers of the 1950s, as companies were exploring the benefits of using them in their operations. IT consultancy emerged in three groups of companies: technology companies, accounting and auditing firms, and management consultancy firms. [@kipping2012 162]

During the second phase, in the 1970s, managers began to employ IT to align internal processes with their organizations' business objectives, clearly pointing to an alignment of IT and strategy. The result was a growing demand for IT consultants with a background in strategy. Furthermore, as new application such as ERPs, CRMs, and accounting software hit the market, IT became recognized as a facilitator of change. IT consultants were working on client's operations and often served as change managers.

The third phase arrived with the introduction of network computing, as the internet fundamentally transformed the nature of commercial transactions. This sparked the rise of a host of 'dot.com consultancies' that provides advice on how to exploit these new opportunities. This third phase differs from the first two as it is mainly driven by new applications and services, and not by new hardware developments. It is during this phase that many IT consulting & outsourcing services became standardized, leading to rapid commoditization and lower prices. New companies began to offer these services on a global scale, often driven by a relatively cheap labor force in emerging economies.

"Where once a company would have spent considerable in-house time on developing their own tailor-made software, most accept that they can buy a ready-made package from a professional software house. Although many companies are still in the grip of major software implementations, our attitudes are changing. Ten years ago we believed that we should adapt software to match our internal processes: nowadays we accept that it is probably quicker, cheaper, and ultimately more effective to adapt our processes to a given package." [@czerniawska1999 23]

"It is already apparent that clients want their 'advisers' to take a much more hands-on role; strategy firms, for example, are constantly exposed over their perceived reluctance to be involved in the implementation of their recommendations." [@czerniawska1999 168]

# Why digital consultancy: Practical perspectives

<!--- Hiring consultancy can be driven from a functionalist perspective, a critical perspective, but also a economic deterministic perspective. First two are in @werr2002 -->

<!-- not the goal to judge if these expectations make sense, rather if the controls they use are fit for purpose -->

An end-to-end consultancy assignment involves many steps. The following overview by @turner1982 involves eight steps and demonstrates how consultancy is external, contingent, relational and involves change.

1.  Provide requested information.
2.  Provide solution to given problem.
3.  Conduct diagnosis that may redefine problem.
4.  Provide recommendations.
5.  Assist with implementation.
6.  Build consensus and commitment.
7.  Facilitate client-learning.
8.  Improve organizational effectiveness.

The fifth goal (implementation) is not without controversy as traditionally, some argued that "one who helps put recommendations into effect takes on the role of manager and thus exceeds consulting's legitimate bounds." [@turner1982] Also, "a frequent dilemma for experienced consultants is whether they should recommend what they know is right or what they know will be accepted." Finally, the author notes that the last three steps are seen as by-products, and often not as explicit goals.

If we go from consultancy, in general, to digital consultancy, it is essential to keep the scope of the definition in mind. Digital consultancy has a much broader scope than merely technological advice and implementation. @swanson2010 [20-25][^2] has described five different ways how consultants can contribute to an organization's innovation process through information technology:

[^2]: @swanson2010 utilizes the term "IT consultancy." However, by ascribing it to both IT-technical and organizational aspects of IT, it inherently refers to "digital consultancy."

-   *Business strategy*: IT consultancy can lead the organization to new pursuits and technologies they wouldn't have discovered themselves. Second, IT consultancy can frame the need for innovation in strategic terms, and they prepare and legitimize the need for change.
-   *Technology assessment*: IT consultancy can facilitate the comprehension of IT technologies and its alternatives.
-   *Business process improvement*: Innovations that involve IT usually come to fruition only after business processes have been revamped. Business process changes usually require an outside-in view and offer rich opportunities for consulting.
-   *Systems integration*: In many cases, introducing a new technology requires that it needs to be integrated with existing systems and users need to be onboarded. This type of IT consultancy usually requires coding skills, hands-on design and implementation expertise
-   *Business support services*: Finally, once the implementation is completed, it can take a while before the solution is entirely assimilated. IT consultants can provide complementary IT services such as support and maintenance until the technology is entirely embedded in the organization.

See also [@bessant1995].

In their 1994 study, for which they interviewed over 100 decision, @lacity1994 [10-17] group expectations with regards to outsourcing into four categories: financial, business, technical and political expectations.

@wood1996 [656] discovered that "consultancies tend to reinforce the strategic strengths of experienced companies rather than compensate for the weaknesses of the inexperienced."

The following sections follow an amended classification by @lacity1994 and rely on research both in (IT) outsourcing and consulting, since many conclusions apply to both. In these situations, it is referred to as working with a "third party." Nevertheless, distinctions are mentioned wherever extrapolating conclusions from the former to the latter is inadequate.

## Financial Expectations

Financial expectations regarding digital consultancy and IT outsourcing are twofold: reducing costs and improving financial control.

### Cost Reduction

The expectation of cost reduction comes from the ability to save on human resources, the ability to eliminate them in times of recession, and not having to pay dues when a new technology needs to be explored and adopted. @lacity1994 [10] found that managers expect that "unit costs are less expensive because of mass production efficiencies and labor specialization." The former applies to outsourcing, but the latter apply to both. For IT outsourcing, it also involves the elimination of large fixed costs during recession and transferring adjustment cost to a third-party [@aubert1996 52].

### Cost Control

The second financial expectation is not necessary about reducing costs, but about controlling them. @sturdy1998 [233] describes how "executives wanting to exercise control over the management and investment of IT, but lacking the expertise." @lacity1994 [10] states that "[i]n most organizations [...] IT costs are controlled through general allocation systems that motivate users to excessively demand and consume resources." No surprise that involving third parties is seen "as a way to contain costs because vendors implement cost controls that more directly tie usage to costs. In addition, users can no longer call their favorite analysts to request frivolous changes but instead must submit requests through a formal cost control process."

@ketler1993 [454] found that some managers see outsourcing as a means of sharing (financial) risks, reducing potential weaknesses in a department. Problems (and associated costs) with staffing, technology and selection are transferred to, or shared with the partner. However, the author also states that other managers rather fear the risk of quality loss, which hints at some kind of trade-off.

Finally, @lacity1994 describes how some managers "wanted to use outsourcing to restructure their IT budgets from lumbering capital budgets to more flexible operating budgets."

## Business Expectations

### Developing Strategy

See @sturdy1998

### Focusing on Core Activities

@furusten2009 [272-273] argues that consultants are often perceived as "relatively stable by [...] employees, stakeholders and other external counterparts", this "builds confidence for the organization. The more stable an organization is experienced as being, the greater its ability to concentrate on its core activities."

### Facilitating Mergers & Acquisitions

Oftentimes, "[m]ergers and acquisitions create many nightmares for IT managers, who are required to absorb acquired companies into existing systems." [@lacity1994 12] Although managers expect that involving third parties for merging IT functions could solve technical incompatibilities and absorb additional employees, the authors found that this was rarely successful.

## Technical Expectations

### Hiring Skilled Individuals

@lacity1994 [12] describes that in many organizations, there is dissatisfaction with in-house IT departments delivering systems late and over budget. In that context, involving third parties is seen as a way to improve technical service. @sturdy1998 [233] agrees and states that managers rely on consultants when their departments are "lacking the skills for a project" or they want to have them "compete with each other."

@aubert1996 [52] found that as specialized firms have digital services as their core business, which is a source of increased efficiency and productivity. E.g. specialized firms can attract highly skilled professionals which are in short supply in the market as a whole.

The sought-after skills are not always technical in nature. More often, it's about being up to date, and spotting emerging trends. @werr2002 [53] found that many organizations expect consultants "to interpret the meaning of technological developments, industry changes and emerging management concepts [...] to the client organization."

@ketler1993 [452] offers another interesting perspective: as the scope of digital services expand, it is difficult or unnecessary for small firms to have a (full-time) expert in each area. Specialized third-party firms, on the other hand, offer a variety of skills and technical knowledge to their clients.

### Knowledge Transfer & Diffusion

In @werr2002 [53], a manager describes how they are often caught up in day-to-day activities, and consultants can help them take a loot at the "big picture", from a strategic perspective: they make sense of the manager's organization in relation to its environment, such as its competitors.

Return to @turner1982.

Something about knowledge transfer here [@sturdy2009].

Nevertheless, there are constraints to knowledge transfer. According to @cohen1990 [128-129], "the ability to evaluate and utilize outside knowledge is largely a function of the level of prior related knowledge [such as] basic skills, or even a shared language but may also include knowledge of the most recent scientific or technological developments in a given field. [...] These abilities collectively constitute what we call a firm's *absorptive capacity*."

@fincham2002 [84] made an interesting observation: organization-specific knowledge and expert knowledge are very complexly related, and knowledge transfer can only happen into a "well-prepared ground." @nooteboom2000 [922] describes this from a transaction cost economics perspective: "[O]ne needs to make investments that are 'specific' to the relation, [...] and a certain durability of the relation is required to set up and recoup the investment." Especially tacit knowledge (impossible to codify or document) suffers from this problem, as it can only be transferred through direct interaction and with hands-on participation by the intended recipient.

"Managers thus viewed consultants as a way of bypassing the knowledge filters created by the organizational hierarchy, as well as the effects of organizational politicals, which became salient in times of reorganization and change. Management consultants were seen as a way for managers to gain a 'true' picture of what was going on in their organizations." [@werr2002 54]

"House consultants also had accumulated a unique understanding of the client company's historical legacies, having a much longer time perspective than individual managers who frequently changed jobs. The consultants were thus described as the 'organizational memory' of the organization."

One of the possible roles of (management) consultants described by @furusten2009 [269] is that of the "carrier": "Carriers of experience, expertise, knowledge, information and data about leadership, management, organization, top-down strategies and holistic perspectives."

## Political Expectations

Finally, there are also reasons that are beyond the business-economical sphere. Oftentimes, individuals want to, or need to, pursue their personal goals within an organization. They might have ideas or plans, and use "the 'objectivity' and/or status of consultants to legitimate or influence a course of action." [@sturdy1998 233]

Political expectations can also come from outside an organization. The use of consultants can instil trust in shareholders and other stakeholders. As @kieser2006 [70] noted: "Companies that are held internally and externally accountable for how they 'handle' uncertainty will contract consultants as a sign of good management. Even patients who principally distrust physicians cannot avoid consulting them."

@lacity1993 [258] also identify a number of political motives, in which managers simply hired consultants to jump on the bandwagon: to react to the efficiency imperative, justify additional resources, react to positive outsourcing media reports or enhance credibility.

@werr2002 [54] describes how consultants can be used as a leading example. They are "valued for energizing the change efforts and pushing the change projects forward. [...] In supporting the realization of change projects, consultants provided methodology as well as an 'energizing example' with their own style of working."

# Why digital Consultancy: Theoretical perspectives

According to @armbruster2006 [3-6], the theoretical perspectives on consultancy can be broken down into two main categories and corresponding streams of literature. The first one is the functionalist view, which sees consultants as "carriers and transmitters of management knowledge." The second perspective argues that the functionalist perspective is to narrow in scope to grasp consulting projects: client-consultants interactions are open to distortions, and understanding them requires research. This is known as the critical view.

```{=html}
<!--
Altijd de link terugleggen naar PA-problemen.
RBV: no knowledge transfer no success
TC: no lower transactions when no transfer
-->
```
## Transaction Cost Economics

Transaction costs economics sees economic organization as a problem of contracting, i.e. organizing economic activity. The starting point is that every transaction comes with certain costs, both ex ante and ex post.

@dahlman1979 [147-148] obtains a classification of transaction costs by going through the different phases of the transaction process.

-   Search & information costs (ex ante): "Two parties [...] search each other out, which is costly in terms of time and resources. If the search is successful [they] must inform each other of the exchange opportunity [...] and the conveying of such information will again require resources."

-   Bargaining & decision costs (ex ante): "Often [...] agreeable terms can only be determined after costly bargaining between the parties involved."

-   Policing & enforcement costs (ex post): "After the trade has been decided on, there will be the costs of policing and monitoring the other party to see that his obligations are carried out as determined by the terms of the contract, and of enforcing the agreement reached."

The last type of transaction costs arises from bounded rationality: it is impossible to estimate both the costs and risks of complete contracts, or even enacting and enforcing them. [@aubert1996 53] The result is that the contractual partners often decide to leave room for adaptation and interpretation, which, in turn, increases the risk of opportunistic behavior (infra).

What follows is that the decision whether a service should be purchased in the market is the result of a comparison of the resulting costs (including transaction costs) with the costs of producing within a "hierarchy". While hierarchies coordinate the flow of materials through sequential steps by controlling it on a higher level in the managerial hierarchy, markets coordinate them through the supply and demand forces between firms [@malone1987 485].

Typically, as they acquire new resources, hierarchies can specialize, resulting in a higher productivity. However, "[a]s a firm gets larger, there may be decreasing returns to the entrepreneur function, that is, the costs of organi[z]ing additional transactions within the firm may rise. [For example, because] the entrepreneur fails to place the factors of production in the uses where their value is greatest." [@coase1937 394-395] The result is that firms increasingly are exposed to costs of internal coordination: "[E]very time that a job which was previously done by one man or one group of men is divided into two or more parts, the problem of coordinating the work of the now separated groups or individuals begins to arise." [@robinson1931 40]

In other words, as companies aim to reduce production costs, by increasing scale, they specialize, albeit increasing coordination costs. If coordination costs would not exist, organizations would grow indefinitely. The result is that blue-collar jobs disappear as production costs are reduced, while white-collar jobs, aimed at coordination, do not. [@canback1998 31-32] Mindful of this evolution, the assumption is that there is a high demand for advice and (IT) solutions that improve coordination within and between firms. These are services in which consultants are particularly well-versed. The question to ask here is: are the transaction costs for working with external consultants lower than internal coordination costs when it comes to improvement of internal coordination and knowledge production?

@canback1998 [37-44] argues it does, and starts from the three critical dimensions of transactions, a popular research topic within transaction cost economics.

*Asset specificity* describes the degree to which physical, human or site assets have a specific usage and can not be put to use for another purpose. With highly idiosyncratic transactions, market forces fail as no vendor is willing to tailor his product or service to one client, and face downward price pressure, since the latter acts as a monopsonist [@robinson1969 218-228], and no buyer is willing to put its faith in the hand of a third party at the risk of being blackmailed. The result is a bilateral monopoly. [@williamson1985 63]

That's why, according to @williamson1979 [250-253] higher asset specificity leads either to one of two forms of "relational contracting". The first form is bilateral governance in which there are "admissible dimensions for adjustment such that flexibility is provided under terms in which both parties have confidence." The second form is unified governance (i.e. internalization or vertical integration), in which "adaptations can be made in a sequential way without the need to consult, complete, or revise inter-firm agreements. Where a single ownership entity spans both sides of the transactions, a presumption of joint profit maximization is warranted."

Initially, @williamson1985 [95-96] identifies 4 sources of asset specificity, but two other sources have been added:

1.  *site specificity*, or the degree to which the successive stages of production are in close proximity to each other;
2.  *physical asset specificity*[^3], or the degree to which the physical properties of the product are unique;
3.  *human asset specificity*, or the degree to which the skills, or configuration of skills within a team, are unique to an organization's production process;
4.  *dedicated assets*, or general investments by the seller which are made with the expectation of a considerable amount of trade with one particular buyer;
5.  *brand capital specificity* [@vita2011 335], or investment in reputation that could be harmed by a vendor delivering bad quality;
6.  *temporal specificity* [@malone1987 486], or the degree to which an asset's value is dependent on it reaching the user within a certain time limit such as shipbuilding or hotel linen delivery.

[^3]: The service sector equivalent is also known as *procedural asset specificity*, or specific routines and workflows tailored to a particular transactional relationship, which are hard to modify or redeploy without value reduction. [@zaheer1995]

The second transaction dimension is its *frequency*. A one-time transaction with high asset specificity does not require a different contracting approach, because there is no subsequent phase in which the buyer/vendor can leverage his monopsony/monopoly power and stray from the initial contract. However, when the frequency goes beyond a single transaction "idiosyncratic transactions are ones for which the relationship between buyer and supplier is quickly thereafter transformed into one of bilateral monopoly." [@williamson1985 241]

*Uncertainty*. Within the context of transaction cost economics, @shin2003 [38] states that "many empirical studies show mixed and contradictory results against what transaction cost economics predicts, especially for the concept of uncertainty." As a solution, he reduces the concept to "behavioral uncertainty", ignoring environmental uncertainty [@watjatrakul2005 391-392]. This is in line with the original interpretation by @williamson1985 [79]: "The proposed match of governance structures with transactions considers only two of the three dimensions for describing transactions: asset specificity and frequency." Uncertainty arises from these two, and together with bounded rationality and opportunism, gives rise to exchange difficulties [@williamson1975 7], making it "more imperative to organize transactions within governance structures that have the capacity to 'work things out.'" [@williamson1985 79] In this context, behavioral uncertainty can't be disentangled from asset specificity. @williamson1985 [78] is fully aware that this is a departure from Coase's transaction cost rationale.

To drive back the theory to the subject of consulting, @canback1998 [37] argues that it's low mainly human asset specificity that favors the use of consultants, referring to their solutions and advice that can easily be reproduced at many organizations.[^4] @watjatrakul2005 [408] put the theory to the test and compared the transaction cost view with the resource-based view (infra) for describing the sourcing decisions in three cases and comes to the following conclusion: "a high-specificity asset has a major impact on sourcing decisions. It overpowers the effect of uncertainty."

[^4]: Furthermore, Canback claims that transaction frequency and uncertainty are less of an influence. By referring to market uncertainty, not only does he obscure the fact that consultants rather thrive in a context with high complexity and uncertainty, he also misrepresents the uncertainty dimension that is central in transaction cost economics. This is a prime example of the vagueness surrounding the concept of uncertainty in transaction cost economics (supra).

Focusing on low-specificity assets allows consultancy firms to achieve economies of scale. That's why they rather shun highly idiosyncratic assignments. Rather, they'll focus on (often high-level) organizational advice and IT architectures, since these have the biggest adaptive properties.

Borrowing rhetoric from the resource-based view (infra), @mata1995 [498] applies Canback's conclusion on technical IT skills: "While technical skills are essential in the use and application of IT, they are usually not sources of sustained competitive advantage. [...] they are usually not heterogeneously distributed across firms. Moreover, even when they are heterogeneously distributed across firms, they are typically highly mobile. [...] firms without the required analysis, design, and programming skills required to make an IT investment can hire technical consultants and contractors." Ergo, digital capabilities are very likely to be outsourced.

@nevo2007 [16-17] also concludes that his research supports the transaction cost hypothesis: "when the internal IT capability is weak, developing and implementing an IT solution is likely to cost more compared with hiring external IT consultants to do the same job."[^5]

[^5]: The reverse situation also supports the identification theory: "IT consultants will not receive the legitimacy they require [...] if their knowledge and expertise do not differ from that possessed by the in-house IT team. Under these circumstances, external IT consultants' impact on IT productivity is expected to be lower." [@nevo2007 17]

## Agency Theory

At the center of agency theory is the observation that the firm is not an individual. *Au contraire,* "the *behavior* of the firm is like the behavior of a market; i.e., the outcome of a complex equilibrium process." [@jensen1976 311] When (the owners of) an organization ask(s) its employees to deliver a service, or buys a service in the market, it encounters the two-pronged principal-agent problem[^6]. By delegating work to an agent, the principal has to account for the fact that "(a) the desires or goals of the principal and the agent conflict and (b) it is difficult or expensive for the principal to verify what the agent is doing." [@eisenhardt1989 58] These phenomena are known as goal incompatibility and information asymmetry.

[^6]: Agency theory is also concerned with the problem of risk sharing that arises when principal and agent each prefer different courses of action due to differing attitudes towards risk. [@eisenhardt1989 58] However, this is not within scope of this paper.

-   *Goal incompatibility*: The organization is interested in a timely roll-out of a quality solution for a problem they have. The consultancy firm, on the other hand, is driven by profit maximization.
-   *Information asymmetry*: consultants wield enormous power over the knowledge that they possess and use. Their clients depend on this knowledge, making them vulnerable, and putting them at mercy of the consultant. [@brien1998] For example, @ylonen2019 [248-249] found that payments from the Finnish Ministry of Finance to a particular consultancy company drastically increased year-over-year, because the consultancy firm had a quasi-monopoly in the knowledge regarding particular remuneration practices. Furthermore, when a particular individual sells his services to another one, it may be difficult to asses its true value [@ouchi1980 134-135]. This is especially the case when interdependent technologies are involved, as their implementation and maintenance requires teamwork. On that account, disentangling individual contribution from the team's joint efforts are particularly hard. This situation invites opportunism such as slacking off.

These phenomena could lead to *adverse selection* on the one hand and *moral hazard* on the other hand. [@rousseau1993 14] The former refers to the contracting of agents "unqualified to fulfill their end of the bargain due to active misrepresentation of the agent's competence and expertise." The latter occurs when "the agent shirks and reduces his or her efforts."

To prevent adverse selection and/or moral hazard, control mechanisms could be put into place, resulting in agency costs. These include the costs of structuring, monitoring, and bonding a set of contracts among agents with conflicting interests, plus the residual loss incurred because the cost of full enforcement of contracts exceeds the benefits." [@fama1983 327] The following expenditures sum up to the total amount of agency costs [@jensen1976 308]:

1.  monitoring expenditures;
2.  bonding expenditures to achieve incentive alignment;
3.  residual loss: the remaining "loss of welfare" of the principal in those situations where the agent makes divergent decisions because it was to expensive to offset it through bonding or monitoring.

Circling back to the this paper's subject of digital consulting, we can summarize the interplay of transaction cost economics and agency theory as follows. Low asset specificity of knowledge production and the improvement of internal coordination mechanisms through IT leads firms to order these services in the market. However, human bounded rationality does not allow for detailed consultancy contracts, since it is impossible for humans to predict the future. Payment for consulting engagements are typically recurring (high frequency), which leads to behavioral uncertainty, since the incentives of the consulting firm and the client do not align (goal incompatibility), their complex interdependent services are hard to evaluate and their contributions are hard to measure (information asymmetry). This could lead to adverse selection and moral hazard, and asks for control mechanisms to economize on agency costs.

Finally, an extra remark is in place. One should not forget that managers are also agents themselves. As @tosi1997 [584] describes: "the reality [is] that in large organizations, owners may be separated from the managers who make decisions in forms, and that the two may have different interests." In that sense, @fincham2002 claims that a consultant can be described as "an agent's agent", extending the management's own agency function. In other words, consultants operate at the "outer reaches of corporate power", stretching corporate authority to its limits. Consequently, their legitimacy is often problematic within the corporation that engages with them.

## Resource-based View

The resource-based view rejects the traditional micro-economic assumptions that resources are homogeneously distributed across firms [@barney1991 99-103]. Instead, it argues that they are heterogeneously distributed, which could allow a firm not only to establish a competitive advantage[^7], but also a sustained competitive advantage when these resources are not perfectly transferable, for example because of resource immobility. These resources come in the form of assets, capabilities or organizational processes. Firms can obtain above-normal results if they can establish a competitive advantage by making their resources exploit opportunities in the market, or neutralize those established by competitors. To be strategic, resources should be valuable, rare, inimitable and non-substitutable.

[^7]: "A firm is said to have a competitive advantage when it is implementing a value creating strategy not simultaneously being implemented by any current or potential competitors." [@barney1991 102]

@mata1995 [495-500] identifies five attributes of information technology as possible sources of sustained competitive advantage for a firm.

1.  Access to capital: IT (or digital) investments can be very expensive and risky. Only a couple of firms might be able to acquire the capital to make these investments, making it a source of sustained competitive advantage.
2.  Proprietary technology: when technology can be kept proprietary, it can be a source of sustained competitive advantage. However, the author states that one the one hand, it's very hard to prevent proprietary IT knowledge from leaking, and on the other hand, IT has become generic more generic. We'd like to add that many organizations' digital ecosystems are peppered with open-source technologies[^8], which is freely available. In other words, for most non-software firms, a sustained competitive advantage through proprietary software is unattainable.
3.  Technical IT skills: the ability to attract and keep technical IT skills that is required to built IT applications. However, these skills are rarely immobile, nor are they really heterogeneously distributed, according to the author.
4.  Managerial IT skills: management's ability to conceive of, develop and exploit IT applications to support and enhance other business functions can enable a firm to manage market risks associated with IT investments. Given the entanglement of business and IT skills, one could say that managerial IT skills are heterogeneously distributed, and that they are immobile.
5.  Customer switching costs: the ability to create a lock-in effect for one's customers through the use of IT. The author states that switching costs, in many situations, are not a source of sustained competitive advantage, as customers will anticipate it, lock-ins create reputation damage and there are many digital alternatives available. However, there are various value-creating attributes that can be achieved through a lock-in. For example, @amit2001 [505-507] describe how customization, two-sided markets, trust-establishing rating systems or virtual communities are features that generated customer switching costs yet are also value generators deemed legitimate.

[^8]: For example, a survey by the European Commission found that around 40% of respondents stated that open-source is the most important source of software development in their organization [@ec2021 191].

@willcocks2003 [188-189] describes how sourcing decision related to technical IT skills depends on both the market for IT consultancy skills and the type of business activity.

-   By market comparison: A high-cost, low-quality market leads to in-house development, while a high-cost, high-quality market should lead to insourcing. A low-cost, low-quality market leads to cheap-sourcing[^9] and a low-cost, high-quality market is perfect for outsourcing.
-   By business activity: non-critical, commoditized applications should be out-sourced. Critical, commoditized applications should be insourced or built in-house, and differentiating, critical applications should be built in-house or acquired.

[^9]: Cheap-sourcing involves low investments and effort, but also comes with no internal learning. For example: development of a new promotional website by a digital agency.

By referring to commoditization, one could say that @willcocks2003 implicitly refers to asset specificity, blending elements of transaction cost economics in the resource based view. @watjatrakul2005 [405-407] makes this explicit by juxtaposing the resource-based view with the transaction cost view. Four types of assets result from this exercise:

1.  Low specificity, non-strategic such as generic managerial capabilities.
2.  Low specificity, strategic such as a configuration of capabilities that result in certain strategic decisions.
3.  High specificity, non-strategic such as an consumer tracking technology that provides valuable insights into the organization's processes.
4.  High specificity, strategic such as company experts that are responsible for developing a organization's differentiating features.

## Identification Theory

The research by @schwarz2005 [311-313] claims that it matters *who* implements an IT project: "technology-enabled inertia can be explained through understanding an employee's social identifications and his or her associated cognitions, where inertia exists on a sliding scale of change." By defending their self-image, low-status groups can hinder the implementation of an application. The sourcing assessment needs to incorporate this finding.

"...competitive pressures, on both clients and consultants, combined with a US culture of anti-intellectualism and 'macho' (grand and unreflective) visions lead to the marketing and adoption of simplistic and necessarily flawed techniques." [@sturdy1998 34]

"Terms such as 'growth' and 'effectiveness' have mythical qualities. They are condensation symbols collapsing a managerial world view into a single word. So, too, [...] consultancy packages [make] use of condensation symbols thereby creating affective bonds to the symbol's object, tying managers into the package at an emotional level and creating a shared managerial language." [@gill1993 290]

"Management consultants, their ideas, and their techniques play a central role in creating the organization in such a way that it is possible to control, change, and 'improve' -- and at the same time, reinforcing a positive managerial identity. While supporting managers in handling their anxieties, some commentators have argued that by reinforcing these, consultants create their own market." [@werr2002 48]

"management consulting is the new and relatively recent attempt to take advantage of the destructured business environment of corporate clients that purchase business services. They represent a semi-institutionalized attempt to advance the professional aspirations of managers themselves, especially in light of the well-publicized attacks on middle management infrastructure that has accompanied the latest corporate downsizing waves." [@leicht2006 35]

"Part of the lure of management consulting lies with the ability to work with highly prestigious business clients on important business problems in an environment well oiled by high fees and salaries." [@leicht2006 37]

## Embeddedness Theory

<!-- Need founding paper here -->

Embeddedness theorists distance themselves from transaction costs economics [@armbruster2006 14-16]. They argue that outsourcing decisions are the byproduct of the relationships between the decision-makers across different companies. Although transaction cost economists stress the importance of trust within relational contracting, it is undersocialized <!-- need citation from granoveter --> according to embeddedness theorists. "As a result, transactions may be inefficient without the participants either noticing or calculating it as such. A transaction cost analysis of such processes may then represent an ex post rationalization of an otherwise inefficient solution." [@armbruster2006 15]

@nooteboom1996 [992] states that typically, economists tend to neglect intrinsic utility and that it doesn't matter who the transaction partner is. Embeddedness theory rejects this, as personality and social embeddedness enter the picture.

Embeddedness solves the adverse selection problem (infra) since "[p]rincipals frequently know their agent's type because of personal familiarity with potential agents or through members of trusted social networks in which both principal and agent are embedded." [@shapiro2005 277]

Several empirical findings support embeddedness theory.

-   See [@armbruster2006 16]

-   See [@kitay2004]

## Sociological neoinstitutionalism

A theory that is systematically drawn upon [@armbruster2006 6-8] is sociological neoinstitutionalism. It is based on the argument that the belief in efficiency of certain practices or solutions drives economic actions, rather than the proven efficiency. For example, @jayatilaka2006 [120] argue that "[i]nitiatives to follow other companies in IS sourcing arrangements could originate from IS and managerial professionals working in the companies and consultants who are aware of successful outsourcing arrangements. Mimetic isomorphism occurs when companies follow the lead of other companies that have successfully outsourced IT."

For example, @loh1992 [350] argues that the decision to outsource their entire IT department to IBM by Eastman Kodak in the late 1980s had a tremendous impact on other companies' outsourcing decisions.

Mimetic isomorphism is driven by three mechanisms [@dimaggio1983 150-154]:

1.  A coercive authority formally or informally exerts pressure on organizations to collude or fall in line. This authority can be governmental (through laws & regulation) and non-governmental (through standard operating procedures established at the conglomerate-level).
2.  Uncertainty regarding technology or organizational processes could drive organizations to "model themselves after similar organizations in their field that they perceive to be more legitimate or successful. The ubiquity of certain kinds of structural arrangements can more likely be credited to the universality of mimetic processes than to any concrete evidence that the adopted models enhance efficiency."
3.  Normative pressures mainly stem from professionalization (infra), as the members of an occupation try to establish a "cognitive base and legitimation for their occupational autonomy."

The result is that large consultancies have been described as carriers, not only of knowledge, but of legitimacy too. After all, it's their analyses that validate management decisions.

"Companies that are held internally and externally accountable for how they 'handle' uncertainty will contract consultants as a sign of good management." [@kieser2006 69]

@zucker1985 [20-21] argues that this is the result of trust-building signals (infra) growing beyond their initial goal of delineating specific expectations. Trust-producing firms (such as consultancy firms) an sich assume a high status, with the business world protecting them against failure.

Clearly, this view is mainly appropriated by the critical view since it raises doubts about the efficient outcomes on the practice of consultancy.

## Signaling Theory

Another theory that falls in the camp of the critical view is that of economic signaling theory [@armbruster2006 8-10]. Unlike sociological institutionalism, it treats the economic actors as experienced and knowledgeable, and not as part of an institution. Signaling theory argues that in uncertain markets, suppliers invest in features that signal status, quality and reliability.

@zucker1985 [15-16] argues that these features can also be used to signal similarity. While nationality, ethnicity and sex can indicate a common cultural system, or a "world held in common", more superficial (bought or acquired) features can delineate specific expectations in specific situations. In consulting this translates into degrees, certificates, using the adequate buzzwords, wearing a suit and driving a quality car. These indicators signal adherence to the "rules of the game."

Sociological neoinstitutionalism argues that legitimacy-seeking behavior leads to inefficient market outcomes, while signaling theory argues the opposite.

# Problem statement

Organizations employing the services of a contingent workforce, like digital consultants, should always be aware of principal-agent problems arising from information asymmetries. This is caused by the fact that a transaction between a vendor and a buying organization involves the delivery of services in the future. As a result, opportunism is always lurking around the corner.

Two types of opportunism can be identified @clark1993 [242]:

1.  Ex ante: Pre-contractual opportunism or adverse selection
2.  Ex post: Post-contractual opportunism or moral hazard

Hiring consultants for digital services deserves a dedicated scope, because of the following five properties that make it very prone to opportunism [@leslie1995 207].

1.  Information technology evolves rapidly. Consequently, it involves a high degree of uncertainty. (ex ante)
2.  The underlying economics of IT changes rapidly, making it hard to evaluate the consultant's contribution. (ex post)
3.  IT has penetrated all business functions. It is hard to isolate it from organizational functions. The question is rarely about "outsourcing or not", but more often about "what tasks will be outsourced, and how". The result is that the responsibilities of in-house staff and consultants is very intertwined. (ex post)
4.  The cost of switching providers are often significant. For example: some consultants have exclusivity for implementing a certain solution. (ex post)
5.  Clients might be very inexperienced with regards to IT (and outsourcing it). This puts them at a disadvantage for selecting and evaluating a consultant (ex ante, ex post).

@aubert1996 [59] also points to a problem of measurement within IT outsourcing. Contracts often specify all kinds of measures: response time, uptime, error logs, etc. Although they are linked to explicit provisions (such as fines, penalties and contract termination), there are two conditions for them to be effective: (1) observability and (2) verifiability. The former implies that the client can observe the actual performance of the agent, while the latter is about verifying observations and providing evidence.

## Adverse Selection

Adverse selection is associated with the client's inability to determine the client's capabilities with regards to the assignment. This analogous to Akerlof's "Lemons problem" [-@akerlof1970]: due to the information asymmetry, clients don't want to pay more than the average price for consultants within a certain niche. While consultants of below-average quality ("lemons") benefit from this average price, above-average consultants will not want to compete, and are crowded out.

[@armbruster2006 69-75] outlines various reasons for quality uncertainty and groups them in two categories.

Category 1: Formal institutional uncertainty

-   Consulting is an unbounded profession.
-   Consulting is an unbounded industry.
-   Consulting has unbounded service lines and product standards.

Category 2: Transactional Uncertainty

-   Confidentiality
-   Product intangibility
-   Interdependent cooperation

The economic barriers to entry [@fee2004 463] in IT consultancy (and consultancy in general) are few to none. Anyone with experience in a specific field, sector or technology can wrap it as advice and sell it to whoever wants to hear it. Furthermore, the author of this paper is unaware of legal barriers to entry.

According to some, assessing the quality of consultants is impossible. For example, according do @bloomfield1995 [40], "there can be no presumed separation between technical skills and political skills, and no ranking between the two in terms of their importance for consultancy practice and the development of IT in user organizations." Furthermore, @bettencourt2002 [101-102] states that for knowledge-intensive business services (KIBS) to succeed, a lot depends on the client. "Client co-production roles [...] are emergent, multi-faceted, and highly collaborative because clients themselves possess much of the knowledge and competence that a KIBS firm needs to successfully deliver its service solution."

For evaluating (future) performance of consultants, one has to rely on informal and relational criteria [@wright2002 277]. According to @clark1993 [250], "the main trust-producing mechanism [...] is the 'closed' social structure; a form of individual trust. The formal, institutional-based, trust-producing mechanisms are weak. It is the contractual guarantees, and the history of past transactions underlying reputation, which overcome the potential effects of adverse selection and moral hazard."

Especially in a situation where past transactions are absent, "management consultancies must convey in some way to their clients that they have something valuable to offer. [...] consultants are able to take control of the process by which impressions and perceptions of their service are created. By managing the creation of these images consultants are able to persuade clients of their value and quality. Management consultancies are therefore 'systems of persuasion' *par excellence* and impression management is not external to the core of their work but is at its core." [@clark1998 35]

In the existing literature, these remarks are part of a critical paradigm regarding consultants [@armbruster2006 4-5]. Authors point to the contestable nature of consulting, the self-interest of consultancy firms, and the stretching of consultancy advice.

See also:

-   [@wright2002]
-   [@david2013]
-   [@mahoney2016]

Another valid point is raised by @basu2011 [23] , who discovered that pre-qualification efforts displayed little effect on adverse selection because the consultant might present an excellent reputation, but individual consultants assigned to a project might lack the required skills.

## Moral Hazard

See also [@armbruster2006 72-73].

Moral hazard is the result from two elements at the core of transaction cost economics and agency theory: the ambiguity of the measurement of individual performance and the goal incompatibility between principal and agent.

When a particular individual sells his services to another one, it may be difficult to asses its true value [@ouchi1980 134-135]. This is especially the case when interdependent technologies are involved, as their implementation and maintenance requires teamwork. On that account, disentangling individual contribution from the team's joint efforts are particularly hard. This situation invites opportunism such as slacking off.

This "ambiguity of the measurement of individual performance" [@ouchi1980 135] is palpable in digital consultancy.

## Corporate Governance & Management Control Systems

In the existing literature, several governance mechanisms have been proposed. Each of them is somehow related to trust[^10] between the business partners. Either they increase trust, or they eliminate the need for trust. From a transaction cost economics perspective, trust makes transactions cheaper and allows for greater flexibility, as it requires less incentivization, and specification and monitoring of contracts [\@nooteboom1996 989].

[^10]: Trust is defined in the broad sense: "the willingness of a party to be vulnerable to the actions of another party based on the expectation that the other will perform a particular action important to the trustor, irrespective of the ability to monitor or control that other party." [@kee1970] If the level of a perceived risk is bigger than the level of trust, the trustor will not engage in a risk-taking relationship.

@liberatore2010 [265] found that building trust, and goal congruence, can help solve the agency problem because it drives the consultancy firm's motivation for short-term profits towards long-term business and reputation. However, trust is not unbounded and should not be taken for granted as it might break down [@nooteboom1996 988]. Golden opportunities that require defection are always lurking and even tempting for the most trustworthy.

@kirilov2012 [193-194] breaks trust factors down in trust-building and trust-sustaining factors. The former is about signaling ability through references, experience and reputation. The latter is about signaling integrity: effective and transparent communication, proactivity, monitoring and consistently meeting contractual obligations. In that sense, building trust can be describe as a "Bayesian-like decision process" in which all trust-relevant information is carefully scrutinized: the proportion of "cooperative choices or long-term behavioral patterns". [@lewicki2006 995]

@williams1988 describes two dimensions to position 'trust': the context and egotism. This yields four sources of trust and cooperation.

|               | Macro                                             | **Micro**                                                   |
|------------------|-------------------------|-----------------------------|
| Egotistic     | Coercion or fear of sanctions from authorities    | Material advantage                                          |
| Non-egotistic | Ethics such as values and norms of proper conduct | Bonds of friendship, kinship of a certain degree of empathy |

As we'll see below, governance mechanisms can be designed to foster each of these four grounds for cooperation.

@shapiro1992 [366-374] identified three bases of trust. Investing in either of these can be matched to the level and benefits of the trust desired, and the costs and risks associated with it. The three bases of trust are the following.

1.  Deterrence-based trust -- or "calculus-based trust" [@lewicki1996 119] -- results in predictive behavior of the agent because there are measures in place to prevent hostile actions. These measures generate a potential cost for acting in a distrustful way, outweighing the advantages of doing so.
2.  Knowledge-based trust emerges from prior contacts based on the premise that through ongoing interaction, partners get to know each other better and develop trust around norms of equity [@gulati1995 92]. People act cooperatively when they expect their partner to behave in the same way and reciprocate. Each has something to give the other. Small gestures, such as a consultant providing market insights, a client inviting consultants to team buildings or company events, pressure each other into conformity [@macaulay1963 63].
3.  Identification-based trust rests on the premise that when both parties share the same preferences they tend to behave in a more trustworthy manner towards each other [@shapiro1992 371]. Several conditions can build trust based on identification, of which joint products or goals, a common team name, proximity and shared values are mentioned explicitly in the research. An interesting finding by @schoenherr2015 [408] is that process integration not only serves as a mechanism for information exchange, but also for engendering reciprocity, yielding greater levels of trust.

According to @lewicki2006 [1011], the bases for trust change over time. For example, as parties get to know each other, their trust evolves from deterrence-based to knowledge-based. However, rarely does a transition occur from knowledge-based trust to identification-based trust, as it requires identification with each other and the development of strong affect between two parties.

This is highly compatible with the research by @mayer1995 [717-720], which describes three groups of trust antecedents: ability, integrity and benevolence.

-   *Ability* describes the skills, competencies and characteristics that enable a party to have influence within a specific domain.
-   *Integrity* involves the trustor's perception that the trustee adheres to the principles that the trustor finds acceptable for that domain.
-   *Benevolence* is the extent to which the trustor believes that the trustee wants to do good to the trustor, and looks beyond their profit motive.

Finally, each of these antecedents maps rather well to the three trust definitions outlined by @sako1992 [37-40]: competence trust, contractual trust and goodwill trust.

Below, a fairly exhaustive list of proposed governance measures is outlined and grouped by their corresponding trust antecedent.

See also @lewicki2006 and @kirilov2012.

Also: how does 'governance' relate to control mechanisms? See @smith2003.

### Ability

#### Reputation

@kirilov2012 [193] describes reputation as "a mixture of the brand name of the enterprise, executive management background, maturity level, customer references, and independent quality assessments."

@armbruster2006 [75-76] distinguishes three types of reputation:

1.  Public reputation is the perception of a consulting firm's (or individual consultant) past performance or potential. For this reason, large consultancies make it known that they spend a lot of resources on the search and selection of recruits. [@kieser2006 91] While there are few to no barriers to enter the market as a whole with a newly-found consulting firm, public reputation is a huge barrier to reaching its upper end. Public reputation is like a public good <!-- citation needed -->; the information is non-excludable and non-rivalrous.
2.  Experience-based trust relates to personal experience with a specific partner. A positive relation drives future action because a partner is less likely to act distrustfully in one transaction if future benefits are jeopardized. [@shapiro1992 367] However, trust evolves slowly, and maintaining it requires commitment. That's why it is often constrained to a small group of business partners. <!-- See also @nooteboom2000. -->
3.  Networked reputation is a firm or consultant's reputation within a network of business relations [@gluckler2003 271]. For example, "if a trusted party cannot provide the resources that are needed, their relations can be used in order to obtain trustworthy information about parties one is not connected to." [@gluckler2003 280] Not only consulting partners can make recommendations; @honer2006 [308] proposes building informal networks that would allow managers to communicate their experience in consulting to each other.

Public reputation has a high market scope, as all potential partners are active in a specific market, but it generally results in less certainty, since public reputation is easily manipulated. Experience-based trust produces high certainty, but a low market scope, since rarely, one has had interpersonal experience with all potential partners. Finally, networked reputation sits somewhere in between: via a social network, one can estimate the reputation of various consulting partners and it also produces high certainty, since relations are at stake.

@clark1993 [243-244] asked 55 respondents about the factors that are important when choosing an executive search & selection consultancy. "Reputation of individual consultants" and "reputation of the consultancy" are in the top three factors. This reputation often arises from "a history of past transactions with individual consultants. Frequent transactions between consultants and clients leads to familiarity which underpins the latters' assessment of the former." In other words, because finding a new consultants implies a search cost [@wilson2012 1072], incumbent consultants are expected to receive new contracts as long as the cost incurred from a potential sub-optimal performance is lower than the search cost of finding a new consultant.

The findings in @clark1993 are confirmed by @richter2009 [285] who found, with regards to projects that involve client-specific information, that "clients are willing to involve external consultants with whom they have established a relationship of trust in the execution of such projects. [...] intermediate forms of governance between the extremes of market procurement from an anonymous provider and fully-fledged integration, are not only viable, but an effective option for clients to procure managerial services." Organizations are more inclined to work with consultants with whom they have no experience when no client-specific information or industry expertise is required. A prior client/supplier working relationship is also listed as an important determinant in the meta-analysis by @lacity2011 [235].

According to @nayyar1990 [516] "reputation performs as an implicit contract. It is enforced by the seller's concerns about future demand for the service provided. [...] reputation is likely to exhibit characteristics of a public good. Once acquired, it can be user over and over again in the context of other services or markets."

According to a survey with 150 German companies [@kieser2006 91], for 73% of respondents, reputation is a deciding factor. Furthermore, 50% of respondents indicated that recommendations from managers of other companies is a deciding factor.

<!-- I need a definition of reputation, and also some research on how reputation can be faked. -->

#### Procurement

"Management consulting is a highly interactive service in which interpersonal trust and 'liking' play a central role. [It is often described] as very similar to recruiting an employee." [@furusten2005 185] Experienced managers buy the services of individuals in whom they have confidence, not from consulting companies. The role if interpersonal is motivated by the argument that the need for consultants is often not driven by the organization, but by the manager's personal needs and insecurities. What is results is the assumption that managers do not always behave in the company's interest when dealing with consultants, and governance measures are required [@honer2006 300]. This ties in to the "agent's agent" argument in @fincham2002, discussed earlier.

@honer2006 [307] describes how a central purchasing/project office which selects consultants on behalf of the managers could streamline the hiring process of consultants. Furthermore, this office could be tasks with control and coordination of all consulting projects, going beyond mere selection. Nevertheless, this could be incongruent with company culture and managerial budget responsibility.

Typically, the involvement of procurement intermediaries commodify[^11] management knowledge [@omahoney2013 205-206]. However, commodification is often resisted on two fronts, both representing a power struggle.

[^11]: Commodification is "the process whereby an object (in the widest sense of the term, meaning a thing, an idea, a creature, etc.) comes to be provided through, and/or represented in terms of, a market transaction", crystalizing their value into a price. [@carvalho2008]]

-   On the one hand, the "producers" of management knowledge, (i.e. the consultancy firms) are well aware that commodification could potentially neglect their competitive advantages, having a deleterious effect on their profit margins.

-   On the other hand, as procurers define the problem of management, the come in direct competition with the managers they represent.

@honer2006 [305-306] found that friction between managers and procurement can result in three behavioral patterns:

-   departmentalism: managers claiming that their department, contrary to the company as a whole, is very transparent regarding their use of consultants.

-   authority protection: managers claiming that intervention ins their authority is neither necessary, nor desired and that they have authority to how their department's problems are solves.

-   laziness: managers do not recognize that using consultants effectively is a significant managerial task, and underreport unsuccessful projects.

#### Third-Party Assessment

@zucker1985 [57-62] describes the rise of the "social overhead sector" in the 20th century. This sector acts as an "intermediary" in a variety of situations: stock brokers, real estate agents, banks, etc. The same principle can be applied to consultants: assessment by a third-party agency can prevent adverse selection.

See [@armbruster2006 76-77].

### Integrity

#### Monitoring

"At the post-contractual stage, agency theory asserts that monitoring the agent gathers information about the agent and helps reduce opportunism. Monitoring places an uncomfortable social pressure on the agent that increases compliance. It also increases the principal's ability to detect the agent's opportunism and thus to appropriately reward or sanction agent behavior. It reduces the agent's motivation to justify a failed strategy, and promotes actions consistent with shareholder goals." [@basu2011 13]

Researchers have emphasized three broad ways in which consultants should be monitored [@basu2011 15]:

1.  When the consultancy firm gives their agreement to the specified deliverables and accompanying deadlines.
2.  During the implementation of a project, the client verifies that the deliverables are being produces according to the original plan by thoroughly and regularly assessing reviews and written and oral progress reports. Meeting with consultants is essential to ensure that consultants share all relevant information in a timely manner.
3.  During the implementation of a project, the client checks that the consultants do not sacrifice quality nor scope to meet deadlines. Furthermore, the originally committed staff should not be changed without approval.

Nevertheless, since monitoring often rely on surrogate measures, consultants can displace their behavior toward these surrogates in order to appear to be behaving well. [@shapiro2005 281]

See also \@nooteboom2000.

#### Contractual Obligations vs. Contract Flexibility

Contracts have several functions [@noteboom1996 924]: a legal document to constrain opportunism, a record of agreement to guide technical coordination, prevention of misunderstanding and even a ritualistic function to seal the intention to cooperate. However, not all future contingencies are known, the cost of setting up a detailed contract and monitoring it can be significant (supra), and contracts may form a straight-jacket that blocks the utilization of future opportunities. Finally, detailed contracts can shroud a contract in an atmosphere of mistrust, derailing the relation before it has even started.

According to @nooteboom1996 [924], most inter-firm cooperation is described in a contract of some form. However, "[t]he question is not so much whether there is a contract, but whats its content is an how elaborate it is."

@mcfarlan1995 claim that it is important to have flexibility in an outsourcing contract, because the target state of a project might change due to evolving technology and business environment. Nevertheless...

@lacity2012 [4] describes that there is substantial evidence that positive outsourcing outcomes are associated with:

-   more detailed contracts with regards to scope, service levels, responsibilities and adaption to change;
-   shorter-term contracts;
-   high-value contracts.

More detailed contracts, when resulting in requirements uncertainty, is an enabler of goal congruence and trust between the consultancy firm and the client, which is found to result in a better project performance [@liberatore2010 264].

#### Purchasing Regulation

See @sturdy2021 [4-5]

@honer2006 [307] proposes setting op standardized processes for dealing with consultants. These would give managers "clear instructions for dealing with consultancy and enhance the principal's control." However, the author highlights that this might impact a manager's perception of their autonomy and they might act in ways to ignore or bypass these rules.

#### Whistleblowing

Also media.

#### Incentivization

Contrary to the design and enforcement of contractual obligations, management by self-interest (i.e. incentivization) "has the advantage that it is cheaper than contracts, is more flexible, and it is in the players' own interest to be seen to comply with agreements." [@nooteboom2000 924] However, it's not a silver bullet as it requires a need for observation, measurement and monitoring. Yet, "How does one measure and monitor degree of dependence, spillovers, and specificity of investments?" It's hard to quantify compensation for such intangible risks. Furthermore, it is hard to maintain, since competences and external conditions are constantly changing.

"Basing the agent's rewards and incentives on imperfect surrogates of performance leads to moral hazard, but aligning the preferences of the agent and the principal through an appropriate reward structure helps curb the agent's opportunistic behavior." [@basu2011 13-15] Several actions are proposed to align incentives: link payment to completion of the promised deliverables, sharing of cost savings or overruns with the consultancy firm, incentives and penalties related to timely completion of a project.

@liberatore2010 [264-266] finds that a higher goal congruence between the consultancy firm and the client is an enabler of project performance.

A particular form of incentivization is "hostage-taking": "one-sided ownership of specific assets may be balanced by one-sided hostages going the other way, or by a rigorous reputation mechanism." [@nooteboom2000 924] When there are no trust-related nor legal enforcement mechanisms, parties can be discouraged from forming long-term relationships. According to @werner1993 [47-48], "hostages" are used in situations where rational behavior would lead to sub-optimal outcome, in the Paretoian sense. In game theoretical terms, hostage-taking is used to prevent defecting behavior.

In terms of the subject of this paper, "hostages" could come in the form of contingent fees. See [@clark1993 243]

See @tosi1997.

Reputation could also be taken hostage. [@shapiro1992 368]

#### Clan Mechanisms

@ouchi1980 proposes to provent opportunism through the establishment of a "clan"[^12], which involves commitment from all parties and eliminates short-term inequities over time. Clans achieve the "union of objectives between individuals which stems from their necessary dependence upon one another. [...] [c]lans display a high degree of discipline [...] achieved through an extreme form of the belief that individual interests are best served by a complete immersion of each individual in the interests of the whole."

[^12]: @ouchi1980 borrows the concept of a clan from @durkheim1997 [127] who gives the term 'clan' to "a horde that has ceased to be independent and has become an element in a more extensive group [...] It is a family in the sense that all the members who go to make it up consider themselves kin to one another [...] The affinities produced by sharing a blood kinship are mainly what keeps them united. What is more, they sustain mutual relationships that might be termed domestic, since these are to be found elsewhere in societies whose family character is undisputed: I mean collective revenge, collective responsibility and, as soon as individual property makes an appearance, mutual heredity."

Clans differ from bureaucracies and markets in that they don't require auditing or evaluation as it takes place "through the kind of subtle reading of signals that is possible among intimate coworkers but which cannot be translated into explicit, verifiable measures." [@ouchi1980 137] For clans to succeed, the following conditions are required: reciprocity, legitimate authority, common values/beliefs and traditions. The former three are normative, while the latter is informal. When these conditions are not met, clans are merely ceremonial and ritualistic.

Within the context of digital consultancy, reciprocity is important in the sense that everybody within a team, both employees and consultants needs to have the freedom to call each other out. Furthermore, managers, product owners and lead developers can assume the role of legitimate authority.

However, both the conditions of traditions and common values/beliefs are the hard to achieve. Mayo already construed in 1945 that "by reason of external circumstance [...] groups [that] have little opportunity to form, the immediate symptom is labor turnover, absenteeism, and the like." [@mayo1945 111] A partial socialization may be accompanied by market or bureaucratic mechanisms [@ouchi1980 138], such as the participation in company meetings, to achieve common values and beliefs.

#### Third-Party Moderation

@babin2017 [6-7] describes a single case study in which trust in an outsourcing relationship had eroded over time. Instead of parting ways, it was clear that both parties needed each other. A proactive approach in the form of a third-party facilitated workshop successfully addressed the trust problem. "When both sides feel hurt, and do not trust the other side, it can be difficult to take preliminary steps to begin to repair inter-organizational trust. An objective outsider using a formal approach proved useful to initiating the trust repair activities.

#### First-Party Assessment

As @mayo1945 [111] describes: "the belief that the behavior of an individual within the factory can be predicted before employment upon the basis of a laborious and minute examination by tests of his technical and other capacities is mainly, if not wholly, mistaken. Examination of his developed social skills and his general adaptability might give better results."

"A second vehicle for improving understanding and predictability between partners is to conduct very good research on the potential partner before a relationship is engaged. This research is directed at assessing the real compatibility, or"interpersonal fit," between partners, as well as assessing the degree to which a potential partner engages in predictable behavior." [@shapiro1992 370]

#### Consulting Database

@sturdy2021 [5] proposes internalization of supplier information. For example, @mohe2006 set up an *infobase* in DaimlerChrysler that can be used by internal managers for managing consultants and consulting projects. It contains news and trends regarding consulting, process guidelines, consultant profiles, past projects and management info (such as price).

@honer2006 [308] proposes an institution within an organization that has the staff and capabilities to support managers in dealing with consultancy. This institution would hold data on previous consultancy engagements, assisting managers in choosing the adequate consultancy partner. Their service is entirely voluntary and secures discrete conduct and sensitivity when dealing with confidential information. This could also be slimmed down

### Benevolence

#### Cultural Understanding

Cultural understanding

#### Psychological Contract Obligations

According to @ang2004 [357], the legal interpretation of an IT outsourcing contract is too limited. Instead, they claim that the construct of a *psychological contract* is more appropriate for analyzing the relationship between an IT service supplier and customer. The concept of a psychological contract states that contracts are "idiosyncratically perceived and understood by individuals [and] [s]ubjectivity in the contract leads to disagreement between parties." [@rousseau1993 21]

Consequently, the psychological contract not only comprises the legal contract, but also the unwritten promises, interpersonal relations, and the individual interpretations and perceptions. Since consultancy contracts can become extremely complex (with project descriptions going into the ten thousands of words), and the involved parties entangled in multiple ways, these intangible aspects can gain prominence. The research in @ang2004 [369-70] outlines several psychological contract obligations that positively impact the success of an outsourced IT project.

-   On the supplier side: (1) clear authority structures, (2) knowledge transfer by educating the customer, (3) building inter-organizational teams.
-   On the customer side: (1) clear specification of requirements, (2) prompt payment, and (3) project ownership and monitoring.

The strength of psychological contract theory is threefold:

1.  it focuses on mutual obligations;
2.  the emphasis is on psychological obligations;
3.  the emphasis is on the individual level--not on the organizations as parties of the contract.

Closely related is the work by @willcockskern [9-13] that makes a distinction between the contractual level and the cooperative level. The contractual level is about payment for the exchange of services and the transfer of assets, information & consultants. The cooperative level involves formal communication mechanisms; personal investments in time, resources & knowledge; mutual goals & objectives and social bonds. The atmosphere surrounding the former is heavily impacted by developments at the latter. A respondent in @willcockskern [9] states that "the contract is a bit like a nuclear deterrent. You need one and you have got to have a framework, but if you've got to use it you are probably in trouble."

#### Relational Contracts

@rousseau1993 [10-12] describes a continuum between transactional contracts and relational contracts. On one end of the continuum, the former is based on "short-term monetizable agreements with limited involvement of each party in the lives and activities of the other." On the other end, the latter describes "agreements based upon exchanges of both socioeconomical and monetizable elements, duration which is open-ended and often long term, and a high degree of flexibility."

### Beyond Controls

#### Professionalization

Professionalization is a mechanism that typically protects clients against self-proclaimed experts but who are unqualified and expose their clients to even greater risks than the ones they are supposed to advice on. [@kieser2006 71] Furthermore, they also protect experts against colleagues that could ruin the reputation of the whole industry. Finally, professionalization typically results in the establishment of an ethos, which fosters[^13] trust between a profession and the public at large [@sokolowski1991] Through these mechanisms, "professions are social devices to limit agency costs." [@shapiro2005 276]

[^13]: A professional ethos is "a set of written and unwritten rules that guide professional practice." [@enstad2017]

Certain countries, like Germany, have made attempts to professionalize the sector through the establishment of specialized university programs to make the use of the title "consultant" dependent on the attainment of specific qualifications. These attempts haven't turned out to be successful: today, consultancy is not yet a profession, not in the classical sense. [@kieser2006 73].

According to a popular functionalist view [@goode1957], which identifies criteria that distinguish professions from occupations: (1) members share a common identity, (2) it's a life-long calling, (3) share common ideals, (4) have a shared self-conception, (5) behave distinctly towards non-members, (6) use specific language, (7) easy to recognize and (8) follow an ethical code by a powerful association.

The power approach, on the other hand, is much different from the functionalist approach. It argues that professions are a group of people that wants to achieve expert status within society, attaining certain privileges. [@kieser2006 75]

Both are potent frameworks for providing arguments why the practice of consultancy is not likely to professionalize. From the functionalist perspective, we identify the following:

-   Consultants do not seek to differentiate themselves from their clients, *au contraire*, they seek partnership, as to truly understand the problems and opportunities a client faces. [@fincham2006]

-   A large part of the *raison d'tre* of consultants relates to their capability of transferring expertise to the clients. This differs from professionals, who are approached by clients to solve a problem, without the expectation of knowledge transfer. [@oakley1993]

-   Consulting organizations are extremely diverse, both in terms of subfields (IT, HR, strategy, ...) and in terms of organization size, structure and business models. [@kieser2006 79, 89]

The arguments of the power approach are the following:

-   On the one hand, there are the small consultancies which could try to establish associations to build up their reputation. On the other hand, there are the big consultancies, with a high reputation, that only stand to lose because of increased competition with (a priori) lower reputation organizations. For this reason, the probability of establishing all-encompassing associations is rather low [@kieser2006 77].

-   Many employees of large consultancy firms see their tenure as a platform to self-employed consultant or partnership at a smaller consultant. A title, or membership of an association would facilitate further split-offs at large consultancies [@kieser2006 80].

One could even argue that professionalization is not even relevant in today's capitalism. The "individual given class status, autonomy, social elevation, in return for safeguarding our well-being and applying their professional judgement on the basis of a benign moral or cultural code [...] no longer exists." [@dent2013, 1-2] Trust and respect in today's professional is "earned through their ability to perform to an externally given set of performance indicators." In that sense, "consultants are the real champions of creating a new professional *appearance*." [@kieser2006 95] By combining a promise of market success and professionalism they are "market professionals".

#### Regulation

-   Three sources of regulation can be identified (@clark1993 246-247).
-   See @muzio2011 [813-817].

While in some countries, like Austria, there is a registration system for consultants, governments have been ambivalent towards professional regulation of the consulting sector [@muzio2011 814]. According to @leicht2006, this is the result of (Western) governments embrace of market logic and their reluctance to intervene with "additional coercive pressures in the wake of questionable professional conduct."

One important antecedent for regulation is professionalization of the sector, which is highly unlikely in the current institutional environment. Although "expertise is increasingly more important in differentiating societies, it is difficult to defend the status of professions, to say nothing of establishing new ones. The trend is towards deregulation and deprofessionalization of existing professions, rather than towards establishing new ones." [@kieser2006 90]

Finally, governments are often large consumers of consultancy services, making them wary of supporting regulation of the sector, as it could drive up prices and reduce their autonomy in hiring them [@muzio2011 815].

#### Government Initiated Codes

See @sturdy2021 [3-4]

#### Self-imposed Sectoral Codes

See @sturdy2021 [4]

#### Specific Commitment

See @sturdy2021 [12]

### Control configurations

See @smith2003 [286-289]

# Research Questions

Abstractie maken van zaken zoals cultuur, bedrijfsgrootte, etc. Link met HR & internaliseren van externen, externe kennis.

1a. Why do Belgian firms rely on digital consultants? 1b. What are inhibitors & enablers for success of digital consultants? 1c. Definition of success

2.  Do Belgian firms see PA problems with digital consultants?
3.  Which control mechanisms do Belgium firms have in place with regards to adverse selection and moral hazard of digital consultants?
4.  Which control mechanisms positively impact success of engaging with a consultancy firm?

Research questions for side projects:

1.  Why do people join a consultancy firm or become an independent consultant?
2.  Do reputational effects exist on the individual consultant level or on the firm level?

# References
